// export const cuisineList = [
//     "American",
//     "BBQ",
//     "Breakfast",
//     "Burgers",
//     "Cafe",
//     "Chinese",
//     "Desserts",
//     "French",
//     "Greek",
//     "Healthy",
//     "Indian",
//     "Italian",
//     "Japanese",
//     "Mexican",
//     "Noodles",
//     "Organic",
//     "Pasta",
//     "Pizza",
//     "Salads",
//     "Seafood",
//     "Spanish",
//     "Steak",
//     "Sushi",
//     "Tacos",
//     "Tapas",
//     "Vegan",
//   ];

  export const cuisineList = [
    "North Indian",
    "South Indian",
    "Breakfast",
    "Dessert",
    "Meals",
    "Breads",
    "Combo",
    "Thali",
    "Special",
    "Fast Food",
  ];